apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: auth-service-policy
  namespace: ecom

spec:
  selector:
    matchLabels:
      app: auth-service

  action: ALLOW

  rules:

  # application traffic
  - from:
    - source:
        principals:
        - cluster.local/ns/ecom/sa/default

  # prometheus scraping
  - from:
    - source:
        principals:
        - cluster.local/ns/monitoring/sa/monitoring-kube-prometheus-prometheus
