apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: api-gateway-monitor
  namespace: monitoring
 
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: api-gateway

  namespaceSelector:
    matchNames:
      - ecom

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
