apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - istio-system

  selector:
    matchLabels:
      app: istiod

  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
