apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: user-service-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:

  namespaceSelector:
    matchNames:
      - ecom

  selector:
    matchLabels:
      app: user-service

  endpoints:

  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
