apiVersion: v1
kind: Secret

metadata:
  name: payment-secret
  namespace: ecom

type: Opaque

stringData:
  DB_USER: root
  DB_PASSWORD: root123
  JWT_SECRET: secret123
  RAZORPAY_KEY_ID: rzp_test_SqlQYRIElPuZio
  RAZORPAY_KEY_SECRET: yOH6eC08nS5I2QZVVur7eMTy
