apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecom
  labels:
    app: api-gateway
spec:
  replicas: 1

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway
        version: v1

      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: api-gateway

          image: sanj231123/api-gateway:v18
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
