apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: ecom
type: Opaque

stringData:
  DB_HOST: mysql
  DB_USER: root
  DB_PASSWORD: root123
  DB_NAME: userdb
  DB_PORT: "3306"
  JWT_SECRET: secret123
