variable "subscription_id" {}
variable "resource_group_name" {}
variable "location" {}
variable "environment" {}
variable "project_name" {}
variable "acr_name" {}
variable "workspace_name" {}
variable "workspace_sku" {}
variable "retention_in_days" {}
variable "cluster_name" {}
variable "dns_prefix" {}
variable "kubernetes_version" {}
variable "node_count" {}
variable "vm_size" {}
variable "storage_account_name" {}
variable "storage_container_name" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "key_vault_name" {}
variable "tenant_id" {}
